spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  logging.level.org:
    hibernate:
      SQL: INFO
      type: INFO
      type.descriptor.sql: INFO
    springframework.jdbc.core:
      JdbcTemplate: INFO
      StatementCreatorUtils: INFO


