server:
  port: 8080
  
spring:
  datasource:
      username: dev
      password: DEVeji6w94
      url: jdbc:mysql://172.17.0.2:3306/cathay?useUnicode=true&characterEncoding=utf-8
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
springdoc:
  packages-to-scan: org.xf.iform.controller
  api-docs:
    path: /api-docs
    enabled: true
    
  swagger-ui:
    path: /swagger-ui
    enabled: true

# App Properties
xfiform.app:
    jwtSecret: xfiformSecretKey
    jwtExpirationMs: 60000 #86400000
    jwtExpirationAllowMs: 6000000
        
    jks-utils:
      jksSource: credentials/cathay/cathayhong.site.jks
      jksPd: tiform
    cathaysaml:
      signingAlgorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
      digestMethod: http://www.w3.org/2000/09/xmldsig#sha1
      samlEndpoint: https://cathayhong.site:8080/api/login/input
      issuer: https://cathayhong.site:8080/api/login/input
      returnUrl: https://cathayhong.site